Proto changes
ankidroid/Anki-Android-Backend pull request #294
Opened 2023-06-16 08:18 UTC by dae

2.1.66 is not due out soon, but I thought I'd do this now while the proto gen changes are fresh in memory.

- Update the backend protobuf generation to match the refactoring done
on the desktop code recently. This involved switching from the Python-based
script to a new one in Rust. Comments from the proto files are now
included in the generated backend bindings.

Also:

- Rumo contributed changes to the upstream Chrono crate which make
it work properly on Android, and these changes have been merged in,
so AnkiDroid no longer needs to pin an older version.
- Update to latest NDK, as latest Rust requires it (closes https://github.com/ankidroid/Anki-Android-Backend/pull/180).
- Update to latest Rust
- Update to Gradle 7, closing #248
- Add a workaround for a crashing bug in the sim caused by the above.
Needs testing to make sure building/running on macOS still works.
- Switch from protobuf to protobuf-lite, which is what Google recommend
for use on Android.
- Add a script to make it easier to reformat Rust code when it fails
checks.

2023-06-16 22:45 UTC, dae commented
Bleh, another failure when cross compiling the Linux archives. Rolling back zstd or the bzip crate may help, but I've run out of time for now.

2023-06-22 12:19 UTC, dae commented
Well that was a saga, but I think I'm getting there. The latest failure looks like it might be solved by bumping the minimum API to 23, which I'm trying now. 

I've been meaning to bring up the supported versions actually - while it's noble to support older devices, given that AnkiDroid barely has enough developer resources as it is, I think it may be worth considering being a bit stricter about the version skew you're willing to support, especially as the tail end comprise only a tiny portion of the userbase. The low API target presumably also causes headaches with dependency updates on the non-backend side, and it's not like those users would suddenly be unable to use the app - it would just mean they'd lose access to updates until they're able to upgrade to a newer device. Thoughts?

2023-06-22 14:22 UTC, BrayanDSO commented
21 + 22 is ~0,26% of our userbase, a pretty small and safe to cut number. 

If it is something important that we can't workaround (e.g. dependencies) or that demands too much work to do, I'm all in favor of cutting older APIs (21 was released almost 10 years ago)

For the current release cycle, I _think_ that we will be able to release 2.16 soon before having to make the API cut, so I'm quite confortable to remove those older APIs.

Pinging @mikehardy, as he may have some more thoughts about this

2023-06-22 14:27 UTC, mikehardy commented
2.16 should go before making minsdkversion changes or merging this, which is just agreeing, if I understand correctly

Fast follows with moving a 2.17 that bumps minsdkver and this change and all sorts of other stuff I hope

2023-06-23 09:42 UTC, dae commented
Finally green :weary:

2023-06-25 00:05 UTC, dae commented
I've noticed that the Windows robo build artifact is missing the dll - need to check whether that's a CI issue, or it's not being built properly.

2023-06-25 00:40 UTC, mikehardy commented
> I've noticed that the Windows robo build artifact is missing the dll - need to check whether that's a CI issue, or it's not being built properly.

Huh - that's unexpected, also seems like it should cause CI to fail! Like there should  be a quick shell test for expected file to exist + be non-zero (or have some expected symbols in it or similar) 🤔

2023-06-25 02:16 UTC, dae commented
There was a check being done for the all-release build, but the issue was only occurring on the current-platform build. Hopefully fixed.

2023-06-28 19:42 UTC, mikehardy commented on rsdroid-testing/build.gradle
> +sourceCompatibility = "1.8"
Just went to JDK17 for build and 11 for source/target compatibility in the AnkiDroid repo, I wonder if that's possible here? It appeared to be compatible with minSdkVersion 21 even

2023-06-28 19:56 UTC, mikehardy commented on build-rust.gradle
> +    if (!System.getenv('ANDROID_NDK_HOME')) {
I have some other projects that rely on NDK and may have different NDK versions that are actually set as ANDROID_NDK_HOME but this requires NDK25 (maybe even strictly 25, but maybe 25+?)

Should there be a check here for the NDK major version (or perhaps complete version) to match either 25+, 25.x or 25.2.9519653 ?

2023-06-28 19:57 UTC, mikehardy commented on .github/workflows/build-all.yml
> +name: Build release (from macOS)
🤔 does the filename `build-all.yml` match the product of running it now, given the name is now `Build release (from macOS)` ?

2023-06-28 20:05 UTC, mikehardy commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-7.6-bin.zip
should go to 7.6.1 now I think?

Also, just curious how adventurous you were, did you try v8.1.1 + and  gradle plugin 8.0.2 - we have JDK17 now, so...may work

2023-06-29 04:36 UTC, mikehardy commented on .github/workflows/build-all.yml
> +name: Build release (from macOS)
I apologize for being a pain, but I have to note these things as I see them 😬 😆  - my release notes in README.md (which are my crib sheet for FutureMike) include a reference this this in form of (for searching)

`Run the Github workflow Build AAR and Robo (all platforms)`

changing that should be included here or MikeFuture will be trying to do something in the wee hours and be confused

2023-06-29 04:41 UTC, mikehardy commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-7.6-bin.zip
FWIW - buildConfig is supported but you have to turn it on like so: https://github.com/ankidroid/Anki-Android/pull/13912/commits/ec1940246b46ceb43800de3185b6810ea1abc3cf#diff-5a90cabaa566821feb87e2e3cf9f9045ac174ceabbf2d10d8a86244f74b1bc49

```groovy
 android {

    buildFeatures {
        buildConfig = true
    }

}
```

Sounds like ANKI_COMMIT_HASH isn't a vital feature in practice (?) so maybe not important, but thought you might be interested

2023-06-29 04:44 UTC, mikehardy commented on build_rust/src/main.rs
> +        panic!("Expected ANDROID_NDK_HOME to point to a 25.x NDK. Future versions may work, but are untested.");
What do you think about leaving our future selves a breakcrumb for the future NDK update?
I probably won't be in these build systems much so I like to leave myself clues whenever possible

```suggestion
        panic!("Expected ANDROID_NDK_HOME to point to a 25.x NDK. Other versions are untested. Edit build_rust/src/main.rs to allow testing.");
```

2023-06-29 04:45 UTC, mikehardy commented
I have now left a second batch of little comments, even nitpickier than the first, but it has to be said this is an amazing batch of work. Again simplifying things while doing the needful on the required updates, and spidering out to get lots of incidental updates - fantastic PR

2023-06-29 04:46 UTC, dae commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-7.6-bin.zip
I'd tried that without luck. Not sure if it's a gradle 8 thing, or I put it in the wrong file. I think I saw mention while Googling that it may be a deprecated approach?

2023-06-29 04:47 UTC, dae commented on build_rust/src/main.rs
> +        panic!("Expected ANDROID_NDK_HOME to point to a 25.x NDK. Future versions may work, but are untested.");
The panic!() will automatically print the file+line number.

2023-06-29 04:54 UTC, dae commented on .github/workflows/build-all.yml
> +name: Build release (from macOS)
I'll push a README update after CI finishes

2023-06-29 05:13 UTC, dae commented on .github/workflows/build-all.yml
> +name: Build release (from macOS)
I thought they'd finished, but I must have been looking at a stale version of the page. Oh well, rebuilding now. :-)

2023-06-29 06:14 UTC, mikehardy commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-7.6-bin.zip
I didn't see anything concrete when I read through related internet conversations and AnkiDroid is definitely using it, it works in gradle 8 in the way I showed so I'm going with it for now. Hopefully it's not a rug-pull in gradle 9 but I'll kick the can on this one. Anyway, was just information - no action needed

2023-06-29 06:17 UTC, mikehardy commented
I need to run these locally myself to test them but having read through all the changes, I preliminarily approve

Appears the main gating items are:

- me testing through this with local builds to make sure I can drive it, and it works
- 2.1.66 anki to actually release (plus update the hash here I suppose?)
- 2.16 AnkiDroid to release (so we can bump minSdkVersion over there and adopt this)

2023-07-01 15:08 UTC, mikehardy commented
As a headsup I'm starting summer travel tomorrow and will have availability but it will be spotty (or it should be! I should be vacationing). I will have more availability at the end of August. I'll focus what time I have on core AnkiDroid maintainer duties (ideally with a full 2.16 release, god help us all...)

2023-07-04 07:48 UTC, dae commented
Turning on link-time optimization has had a nice impact on the backend size:

Before:
40M     rsdroid/build/generated/jniLibs/x86_64/librsdroid.so
58M     rsdroid-testing/build/generated/jniLibs/librsdroid.so

After:
19M     rsdroid/build/generated/jniLibs/x86_64/librsdroid.so
25M     rsdroid-testing/build/generated/jniLibs/librsdroid.so

2023-08-02 17:33 UTC, BrayanDSO commented
After building the backend and being able to wander around the app with it, I tried to run tests and I got the following error (Windows 11):

```
> Could not resolve all files for configuration ':AnkiDroid:playDebugUnitTestCompileClasspath'.
   > Failed to transform rsdroid-testing-0.1.22-anki2.1.66.jar to match attributes {artifactType=android-classes-jar, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for IdentityTransform: C:\Users\braya\StudioProjects\Anki-Android-Backend\rsdroid-testing\build\libs\rsdroid-testing-0.1.22-anki2.1.66.jar.
         > File/directory does not exist: C:\Users\braya\StudioProjects\Anki-Android-Backend\rsdroid-testing\build\libs\rsdroid-testing-0.1.22-anki2.1.66.jar
```

After renaming the `rsdroid-testing.jar` file in the same directory to `rsdroid-testing-0.1.22-anki2.1.66.jar`, everything worked, so I ask it was an error of my part, or in my environment, or in the build scripts

2023-08-02 17:34 UTC, BrayanDSO commented
Also, rename `build-aar` to `build` in the `check-droid` files

2023-08-02 23:33 UTC, dae commented
It looks like the version number is no longer included in the test build output, so I'll pushed a change to Anki-Android to look for the versionless filename instead.

2023-08-20 19:24 UTC, david-allison requested changes
Testing notes on an M1 mac. 

**⚠️ Major**

**Issue**: only x86_64/librsdroid.so` is output into `resdroid-release.aar`, but I'm using an `aarch64` emulator.

**Result**
`Anki-Android` fails: `dlopen failed: library "librsdroid.so" not found`

----
**Minor**

`RELEASE=1` performs subsets of the build under debug mode.

```
davidallison@Davids-MBP Anki-Android-Backend % RELEASE=1 ./build.sh
    Finished dev [unoptimized + debuginfo] target(s) in 0.07s
     Running `target/debug/build_rust`
```


**ALL_ARCHS fails** (probably no point in fixing this one)
`ALL_ARCHS=1` fails with  `error: failed to run custom build command for `ring v0.16.20``

<details><summary>trace</summary>

```
error: failed to run custom build command for `ring v0.16.20`

Caused by:
  process didn't exit successfully: `/Users/davidallison/StudioProjects/Anki-Android-Backend/anki/out/rust/release/build/ring-31e80f5cceb7cb69/build-script-build` (exit status: 101)
  --- stdout
  OPT_LEVEL = Some("3")
  TARGET = Some("x86_64-unknown-linux-gnu")
  HOST = Some("aarch64-apple-darwin")
  cargo:rerun-if-env-changed=CC_x86_64-unknown-linux-gnu
  CC_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CC_x86_64_unknown_linux_gnu
  CC_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=TARGET_CC
  TARGET_CC = None
  cargo:rerun-if-env-changed=CC
  CC = Some("x86_64-unknown-linux-gnu-gcc")
  cargo:rerun-if-env-changed=CFLAGS_x86_64-unknown-linux-gnu
  CFLAGS_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CFLAGS_x86_64_unknown_linux_gnu
  CFLAGS_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=TARGET_CFLAGS
  TARGET_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")

  --- stderr
  running "x86_64-unknown-linux-gnu-gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "include" "-Wall" "-Wextra" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-fstack-protector" "-g3" "-DNDEBUG" "-c" "-o/Users/davidallison/StudioProjects/Anki-Android-Backend/anki/out/rust/x86_64-unknown-linux-gnu/release/build/ring-4c6bad2af88b1c90/out/aesni-x86_64-elf.o" "/Users/davidallison/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ring-0.16.20/pregenerated/aesni-x86_64-elf.S"
  thread 'main' panicked at 'failed to execute ["x86_64-unknown-linux-gnu-gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "include" "-Wall" "-Wextra" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-fstack-protector" "-g3" "-DNDEBUG" "-c" "-o/Users/davidallison/StudioProjects/Anki-Android-Backend/anki/out/rust/x86_64-unknown-linux-gnu/release/build/ring-4c6bad2af88b1c90/out/aesni-x86_64-elf.o" "/Users/davidallison/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ring-0.16.20/pregenerated/aesni-x86_64-elf.S"]: No such file or directory (os error 2)', /Users/davidallison/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ring-0.16.20/build.rs:653:9

```
</details>

2023-08-20 20:44 UTC, david-allison commented on build_rust/src/main.rs
> +        &["-t", "aarch64"]
Fixes for macOS M1 build

```suggestion
    } else if cfg!(all(target_os = "macos", target_arch = "aarch64")) {
        add_rust_targets(&["aarch64-linux-android"])?;
        &["-t", "arm64-v8a"]
```

2023-08-20 22:09 UTC, david-allison reviewed
I'm happy to merge these changes, barring one change to get this building on aarch64 (above)

2023-08-20 22:09 UTC, david-allison commented on gradlew
> +#!/bin/sh
nit: may want `gitattributes=true` for these files (set in `.gitattributes`) so they're hidden from the diffs

2023-08-21 00:53 UTC, david-allison approved these changes
This feels like it can be marked as "ready to review" now 2.16 is out

🚀🚀

2023-08-21 01:04 UTC, dae commented
> RELEASE=1 performs subsets of the build under debug mode.

That's intended - we want the output artifacts to be built in release mode, but not build_rust, as building it in release mode would be slower than any minor runtime savings it might have.

2023-08-21 04:20 UTC, dae commented
I'm not sure what's suddenly broken the build. Will investigate when I have a chance.

2023-08-21 06:31 UTC, dae commented
I have no idea what happened there, but the upgrade seems to have fixed it. :man_shrugging:

2023-08-22 18:51 UTC, mikehardy commented
Testing note: I just ran through the buid on the M1 machine in the house, along with the corresponding Anki-Android build (using the coordinated PR there...) and ran `./gradlew jacocoTestReport` and everything worked

So I think macOS apple silicon is ✅  now

I'll check intel mac and windows to make sure they're still good then approve...

2023-08-22 23:36 UTC, mikehardy commented on README.md
As long as we're helping people set the NDK, this is what I had to do on windows in powershell

````suggestion
Or Windows using Powershell:

```
$env:ANDROID_NDK_HOME="env:ANDROID_SDK_ROOT\ndk\25.2.9519653"
```
````

2023-08-22 23:58 UTC, mikehardy approved these changes
worked for me on macos M1 + intel, as well as windows. I assume linux will work (it's tested in CI plus I think you use it @dae ?). I use it frequently as well, happy to help fuzzbust if I'm wrong about it working

2023-08-23 00:08 UTC, dae commented
Yep, Linux is my main dev box again these days.

2023-08-23 02:51 UTC, mikehardy commented
Hey @dae - I don't think bisectability is such a concern there and I like just about every commit in the chain. Leaning towards rebase, but could squash. You have a preference? After that I'll publish likely tomorrow (nearly bedtime here now...)

2023-08-23 13:53 UTC, merged

2023-08-23 13:54 UTC, mikehardy commented
I'll try to get a release out today, then I/we can modify the Anki-Android PR to point at the new artifact

2023-08-23 13:54 UTC, mikehardy commented
What a huge improvement, wow! Thank you

2023-12-08 16:54 UTC, david-allison commented
@dae (minor, don't spend time on it if it's not an instant answer)

Do you recall why `buildConfig` was removed in https://github.com/ankidroid/Anki-Android-Backend/commit/c495fd05e0b745e868a27382a1b50c51a0665657

It compiled with the following, but don't know whether it was removed due to a problem downstream:

```patch
Subject: [PATCH] Bump version to 0.1.30-anki23.10.1
---
Index: rsdroid/build.gradle
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/rsdroid/build.gradle b/rsdroid/build.gradle
--- a/rsdroid/build.gradle	(revision 3dc1379468fc7f6322b7ddc79e080a516486b490)
+++ b/rsdroid/build.gradle	(date 1702053780640)
@@ -17,11 +17,22 @@
     return commit
 }
 
+def getAnkiDesktopVersion() {
+    Properties properties = new Properties()
+    properties.load(project.rootProject.file('gradle.properties').newDataInputStream())
+    def versionName = properties.getProperty('VERSION_NAME')
+    return versionName.substring(versionName.indexOf("anki") + "anki".length())
+}
+
 android {
     namespace 'net.ankiweb.rsdroid'
     compileSdk rootProject.ext.compileSdk
     ndkVersion "26.1.10909125" // Used by GitHub actions - avoids an install step on some machines
 
+    buildFeatures {
+        buildConfig true // expose 'ANKI_DESKTOP_VERSION'
+    }
+
     compileOptions {
         sourceCompatibility JavaVersion.VERSION_11
         targetCompatibility JavaVersion.VERSION_11
@@ -34,6 +45,7 @@
         versionName VERSION_NAME
 
         consumerProguardFiles "consumer-rules.pro"
+        buildConfigField "String", "ANKI_DESKTOP_VERSION", "\"" + getAnkiDesktopVersion() + "\""
     }
 
     buildTypes {
```

2023-12-08 21:37 UTC, dae commented
I believe it broke when Gradle was updated. If your changes or the passage of time got it working again, and you plan to use it, feel free to add it back.