23.10 stable
ankidroid/Anki-Android-Backend pull request #314
Opened 2023-10-28 05:43 UTC by dae

Drafting until stable release.

2023-10-28 05:52 UTC, dae commented
I'll need to verify sdk 26 works.

2023-10-28 20:48 UTC, dae commented
Well, 14 hours later, GitHub appear to have made NDK 25 the default again. :shrug:

2023-10-28 21:11 UTC, dae commented
No, it's more frustrating than that - it seems that the runners are a heterogeneous mix of 25 and 26. :facepalm:

2023-10-31 16:32 UTC, mikehardy approved these changes
LGTM pending stable commit hash I suppose?

2023-10-31 16:36 UTC, mikehardy commented on .github/workflows/build-quick.yml
> +        run: Add-Content -Path $env:GITHUB_ENV -Value ANDROID_NDK_HOME=$env:ANDROID_NDK_LATEST_HOME
I'm sure this will give us some unexpected interaction with NDK 27 (or 26.2+) at some point but

1- can't think of a better way to pin it while they roll out the image
2- it'll just fail fast in the `panic` version check below with a clean message so it won't be mysterious or anything

So, works for me

2023-10-31 16:56 UTC, mikehardy requested changes

2023-10-31 16:56 UTC, mikehardy commented on build_rust/src/main.rs
> +        panic!("Expected ANDROID_NDK_HOME to point to a 26.x NDK. Future versions may work, but are untested.");
Needs corresponding change in docs

https://github.com/ankidroid/Anki-Android-Backend/blob/080cfb99ffe49278d7bf33803f1e2aac23dcb7a0/README.md?plain=1#L56

https://github.com/ankidroid/Anki-Android-Backend/blob/080cfb99ffe49278d7bf33803f1e2aac23dcb7a0/README.md?plain=1#L92-L104

2023-10-31 22:32 UTC, dae commented
Ready to go

2023-10-31 22:51 UTC, dae commented
Please try rerun the Windows one to confirm if it's a flake or something I'll need to dig into.

2023-11-01 00:03 UTC, david-allison commented
Rerunning

2023-11-01 13:47 UTC, mikehardy approved these changes
LGTM - awesome!

2023-11-01 13:47 UTC, merged