Include list of TS backend calls in artifacts directory
ankidroid/Anki-Android-Backend pull request #434
Opened 2024-11-03 13:05 UTC by voczi

Currently we have no way of knowing what backend functions we should support for the TS scripts in the Anki backend, beyond manually checking the code. This PR adds a list of function names that we should have bindings for in [PostRequestHandler.kt](https://github.com/ankidroid/Anki-Android/blob/main/AnkiDroid/src/main/java/com/ichi2/anki/pages/PostRequestHandler.kt), to the Anki artifacts directory in a file named "ts_funcs.txt". In the Anki-Android repo, we should add a test to verify that the keys of our mappings in PostRequestHandler correlate to the list in the artifact directory.
Also, we can use the crates from this PR (oxc_*) for other TS-related things. Considering the fact that the Anki ecosystem is moving to TS+Svelte, it could very well come in handy in the future.

2024-11-03 13:31 UTC, voczi commented
Need to account for scripts inside Svelte pages, too?
https://github.com/ankitects/anki/blob/8b84583433d6400e64359dccfe1e2edde3df3e34/ts/routes/import-page/ImportPage.svelte#L13

2024-11-03 13:40 UTC, mikehardy commented
Yeah, `importDone` looks like a real symbol, perhaps ignore `pb` things in generated as that's protobuf? But include the other `@generated` items. 

I like where this is going though, it's similar to our Activity startup test. It was built to reproduce a real bug and has caught bugs before via this sort of "automated checking of universe of all possibilities" approach that scans for list of "should work" items then verifies they're handled...

2024-11-03 13:43 UTC, voczi commented
Considering another approach: https://tree-sitter.github.io/tree-sitter/
**Very** interesting project. Look at the list of parsers: https://github.com/tree-sitter/tree-sitter/wiki/List-of-parsers

2024-11-03 13:52 UTC, mikehardy commented
That looks pretty incredible yeah, drive-able in rust (apparently), can get AST of svelte or typescript? Appears to fit the bill
Between this and the PR where you took my grep and said "nope" then replaced it with proper XML parsing I'm starting to think you are a real programming language academic-type nerd! 👍 . Can't argue with it, this looks like the right sort of approach

2024-11-03 16:09 UTC, voczi commented
`ts_imported_funcs` is a mess. But.. at least it works? Or something? I don't know.
Here's how ts_funcs.txt looks like right now:
```
i18nResources
latestProgress
getSchedulingStatesWithContext
setSchedulingStates
cardStats
getChangeNotetypeInfo
getNotetypeNames
changeNotetype
getChangeNotetypeInfo
getNotetypeNames
congratsInfo
getDeckConfigsForUpdate
updateDeckConfigs
getDeckConfigsForUpdate
addImageOcclusionNote
updateImageOcclusionNote
getImageForOcclusion
getImageOcclusionNote
getImportAnkiPackagePresets
getCsvMetadata
getDeckNames
getNotetypeNames
getCsvMetadata
getFieldNames
importCsv
getCsvMetadata
getDeckNames
getNotetypeNames
importJsonFile
importJsonString
searchInBrowser
computeFsrsParams
computeOptimalRetention
simulateFsrsReview
evaluateParams
setWantsAbort
getGraphPreferences
graphs
setGraphPreferences
importAnkiPackage
importDone
```

2024-11-03 19:53 UTC, voczi commented
Useful for future work: https://tree-sitter.github.io/tree-sitter/playground

2024-11-05 14:21 UTC, mikehardy requested changes
looks pretty good, couple comments

needs a rebase to main after anki24.10rc2 merges, and should contain a gradle.properties bump to the local part of the version number, as you're adding a cool feature here so it should be a distinct version

2024-11-05 14:21 UTC, mikehardy commented on build_rust/src/main.rs
> +        let name = captures.get(0).unwrap().node.utf8_text(code_bytes).unwrap();
Hey @voczi - I'm unsure exactly how this works in the anki-upstream / Anki-Android-Backend context, but I know in typescript it is possible to have multiple comma-separated named imports, but if I am reading this correctly only the first named import is seen here?

2024-11-05 14:21 UTC, mikehardy commented on build_rust/src/main.rs
> +        String::from_utf8(read_file(Path::new("build_rust/queries/ts_imports.scm")).unwrap())
I do a lot of directory tree browsing and if I see just "queries" I'll think it's generic but we're just storing tree sitter queries, propose directory rename queries -> tree_sitter_queries

Also, all bike sheds should have murals painted on them by local graffiti artists, funded by city grants, but only by those artists that promise not to tag historical buildings.

2024-11-05 14:38 UTC, voczi commented on build_rust/src/main.rs
> +        let name = captures.get(0).unwrap().node.utf8_text(code_bytes).unwrap();
I assume that every unique pair of captures is iterated here. So if you have something like
`import { importDone, doXYZ } from "@generated/backend";`
Then you get a match where name="importDone"&src="@generated/backend" and another where name="doXYZ"&src="@generated/backend".
I should double-check this.

2024-11-05 14:39 UTC, voczi commented on build_rust/src/main.rs
> +        String::from_utf8(read_file(Path::new("build_rust/queries/ts_imports.scm")).unwrap())
> I do a lot of directory tree browsing and if I see just "queries" I'll think it's generic but we're just storing tree sitter queries, propose directory rename queries -> tree_sitter_queries

Sure!

> Also, all bike sheds should have murals painted on them by local graffiti artists, funded by city grants, but only by those artists that promise not to tag historical buildings.

WHAT

2024-11-05 15:23 UTC, mikehardy commented on build_rust/src/main.rs
> +        String::from_utf8(read_file(Path::new("build_rust/queries/ts_imports.scm")).unwrap())
I am the GOAT of bike shed color choosers and just wanted to demonstrate my unmatchable power

Managed to delegate color choice to something that can't be judged (it's art!) with decision process speed determined by a government committee. Beat that.

2024-11-05 15:59 UTC, voczi commented on build_rust/src/main.rs
> +        String::from_utf8(read_file(Path::new("build_rust/queries/ts_imports.scm")).unwrap())
LGTM 🚀

2024-11-05 17:07 UTC, mikehardy commented on build_rust/src/main.rs
> +        let name = captures.get(0).unwrap().node.utf8_text(code_bytes).unwrap();
if you double-checked and it's good I'm +1 for ship

2024-11-05 18:52 UTC, merged